### ISSUE TITLE
Duplicated book reward

### ISSUE THREAD

**Issue by Remodor** [zeobviouslyfakeacc/ShorterReadingIntervals#1]
I checked this twice with and without the mod. Finishing the 4h book for rifles gave twice the level increase.
I did not check any other books, but should be the same, doubling the effectiveness of books..

Replicate:
- Start survival game.
- Give rifle book lvl 4.
- Finish book with the mod -> lvl 2.
- Finish book without the mod -> lvl 1.5

**Comment by zeobviouslyfakeacc** [comment]
Indeed, thank you for bringing this to my attention! Fixed in the aforementioned commit 🚀
